In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('data/netflix_titles.csv', engine="python")
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

In [11]:
df.shape

(8807, 12)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [13]:
df["type"].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [14]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df_clean = df.copy()

### Eliminar Nulos

In [17]:
df_clean["director"].fillna("Unknown", inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_27880\1265887643.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean["director"].fillna("Unknown", inplace=True)

In [18]:
df_clean["cast"].fillna("Unknown", inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_27880\2766125273.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean["cast"].fillna("Unknown", inplace=True)

In [19]:
df_clean["country"].fillna("Unknown", inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_27880\249494371.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean["country"].fillna("Unknown", inplace=True)

In [20]:
df_clean.dropna(subset=["date_added"], inplace=True)

In [21]:
df_clean.dropna(subset=["rating"], inplace=True)

In [22]:
df_clean.dropna(subset=["duration"], inplace=True)

In [23]:
df_clean.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

### TIPOS DE DATOS

In [24]:
df_clean["date_added"].sample(10)

8200     February 21, 2018
1177        March 20, 2021
4636    September 14, 2018
4779          July 8, 2018
3211     November 29, 2019
5580        March 10, 2017
8736       January 1, 2017
4104     February 15, 2019
8009         July 18, 2019
6888       October 1, 2020
Name: date_added, dtype: object

In [25]:
df_clean["date_added"].str.strip()

0       September 25, 2021
1       September 24, 2021
2       September 24, 2021
3       September 24, 2021
4       September 24, 2021
               ...
8802     November 20, 2019
8803          July 1, 2019
8804      November 1, 2019
8805      January 11, 2020
8806         March 2, 2019
Name: date_added, Length: 8790, dtype: object

In [26]:
for col in df_clean.select_dtypes(include="object").columns:
    con_espacios = df_clean[col].str.startswith(" ").sum() + \
                   df_clean[col].str.endswith(" ").sum()
    if con_espacios > 0:
        print(f" '{col}' tiene {con_espacios} valores con espacios extra")

 'date_added' tiene 88 valores con espacios extra

In [27]:
#limpio los espacios de date_added y lo convierto a formato fecha
df_clean["date_added"] = df_clean["date_added"].str.strip()
df_clean["date_added"] = pd.to_datetime(df_clean["date_added"], errors='coerce')

In [28]:
for col in df_clean.select_dtypes(include="object").columns:
    con_espacios = df_clean[col].str.startswith(" ").sum() + \
                   df_clean[col].str.endswith(" ").sum()
    if con_espacios > 0:
        print(f" '{col}' tiene {con_espacios} valores con espacios extra")
    else:
        print(f"'{col}' no tiene valores con espacios extra")

'show_id' no tiene valores con espacios extra
'type' no tiene valores con espacios extra
'title' no tiene valores con espacios extra
'director' no tiene valores con espacios extra
'cast' no tiene valores con espacios extra
'country' no tiene valores con espacios extra
'rating' no tiene valores con espacios extra
'duration' no tiene valores con espacios extra
'listed_in' no tiene valores con espacios extra
'description' no tiene valores con espacios extra

In [29]:
# Extraigo las columnas para la fecha
df_clean["year_added"] = df_clean["date_added"].dt.year
df_clean["month_added"] = df_clean["date_added"].dt.month
df_clean["month_name"] = df_clean["date_added"].dt.month_name()

In [30]:
#como el mes sale alfabeticamente en ingles, creo un diccionario para mapearlo a español

meses = {
    1:"enero", 2:"febrero", 3:"marzo", 4:"abril",
    5:"mayo", 6:"junio", 7:"julio", 8:"agosto",
    9:"septiembre", 10:"octubre", 11:"noviembre", 12:"diciembre"
}

df_clean["month_name"] = df_clean["month_added"].map(meses)

In [31]:
df_clean.sample(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,month_name
3728,s3729,Movie,The End of Evangelion,"Hideaki Anno, Kazuya Tsurumaki","Megumi Ogata, Kotono Mitsuishi, Megumi Hayashi...",Japan,2019-06-21,1997,TV-MA,87 min,"Action & Adventure, Anime Features, Internatio...","Seele orders an all-out attack on NERV, aiming...",2019,6,junio
678,s679,TV Show,The Assassination of Gianni Versace,Unknown,"Edgar Ramírez, Darren Criss, Ricky Martin, Pen...",United States,2021-06-19,2018,TV-MA,1 Season,"Crime TV Shows, TV Dramas, TV Thrillers","Defining moments in Andrew Cunanan's life, sta...",2021,6,junio

In [32]:
df_clean["release_year"] = df_clean["release_year"].astype(int)

In [33]:
#como la duracion se separan en horas y season las voy a separar en numero y texto
df_clean["duration_value"] = df_clean["duration"].str.extract(r"(\d+)").astype(int)
df_clean["duration_unit"] = df_clean["duration"].str.extract(r"([a-zA-Z]+)")

In [34]:
df_clean.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,month_name,duration_value,duration_unit
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,9,septiembre,90,min
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,9,septiembre,2,Seasons
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,9,septiembre,1,Season
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,9,septiembre,1,Season
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,9,septiembre,2,Seasons

In [35]:
# listed_in tiene multiples generos separados por coma
# Extraigo el genero principal (el primero)
df_clean["primary_genre"] = df_clean["listed_in"].str.split(",").str[0].str.strip()

In [36]:
df_clean.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,month_name,duration_value,duration_unit,primary_genre
2344,s2345,Movie,Nobody Knows I'm Here,Gaspar Antillo,"Jorge García, Millaray Lobos, Luis Gnecco, Ale...",Chile,2020-06-24,2020,TV-MA,92 min,"Dramas, Independent Movies, International Movies","A former child singer, traumatized by his expe...",2020,6,junio,92,min,Dramas
1280,s1281,Movie,Pelé,"David Tryhorn, Ben Nicholas",Unknown,United Kingdom,2021-02-23,2021,TV-14,109 min,"Documentaries, International Movies, Sports Mo...",Against the backdrop of a turbulent era in Bra...,2021,2,febrero,109,min,Documentaries
822,s823,Movie,The Wind,Emma Tammi,"Caitlin Gerard, Julia Goldani Telles, Ashley Z...",United States,2021-06-02,2019,R,88 min,Horror Movies,Isolated on a wind-ravaged 19th-century homest...,2021,6,junio,88,min,Horror Movies
712,s713,Movie,Silver Skates,Michael Lockshin,"Fedor Fedotov, Sonya Priss, Yury Borisov, Kiri...",Unknown,2021-06-16,2020,TV-MA,138 min,"Action & Adventure, Dramas, International Movies",On the frozen rivers and canals of St. Petersb...,2021,6,junio,138,min,Action & Adventure
6397,s6398,Movie,Cabin Fever,Travis Zariwny,"Gage Golightly, Matthew Daddario, Samuel Davis...",United States,2019-06-06,2016,R,98 min,"Horror Movies, Thrillers",As a flesh-eating virus rips its way through a...,2019,6,junio,98,min,Horror Movies

In [37]:
df_clean.drop_duplicates(inplace=True)
df_clean.duplicated().sum()

np.int64(0)

In [38]:
#solo para verificar
print(f"Filas originales : {df.shape[0]}")
print(f"Filas limpias    : {df_clean.shape[0]}")
print(f"\nNulos restantes:\n{df_clean.isnull().sum()[df_clean.isnull().sum() > 0]}")
display(df_clean.sample(5))

Filas originales : 8807
Filas limpias    : 8790

Nulos restantes:
Series([], dtype: int64)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,month_name,duration_value,duration_unit,primary_genre
1679,s1680,Movie,Singham,Rohit Shetty,"Ajay Devgn, Kajal Aggarwal, Prakash Raj, Sonal...",India,2020-11-19,2011,TV-14,142 min,"Action & Adventure, Dramas, International Movies",A police inspector kills himself after a power...,2020,11,noviembre,142,min,Action & Adventure
3927,s3928,TV Show,New Girl,Unknown,"Zooey Deschanel, Jake Johnson, Max Greenfield,...",United States,2019-04-11,2018,TV-14,7 Seasons,"Romantic TV Shows, TV Comedies","Still rebounding from a breakup, Jessica Day m...",2019,4,abril,7,Seasons,Romantic TV Shows
2549,s2550,Movie,John Henry,Will Forbes,"Terry Crews, Ludacris, Jamila Velazquez, J.J. ...",United States,2020-05-09,2020,R,92 min,"Dramas, Thrillers",A reformed LA gang member upends his peaceful ...,2020,5,mayo,92,min,Dramas
6592,s6593,Movie,Den of Thieves,Christian Gudegast,"Gerard Butler, Pablo Schreiber, O'Shea Jackson...",United States,2020-05-01,2018,R,140 min,Action & Adventure,A highly skilled crew of bank robbers plotting...,2020,5,mayo,140,min,Action & Adventure
7102,s7103,Movie,Issaq,Manish Tiwary,"Prateik, Amyra Dastur, Ravi Kishan, Prashant N...",India,2018-03-01,2013,TV-MA,140 min,"Dramas, International Movies, Music & Musicals",Two young lovers in Banaras are caught in the ...,2018,3,marzo,140,min,Dramas

### EXPORTAR

In [39]:
import csv

df_clean = df_clean.replace("\n", " ", regex=True)

df_clean.to_csv(
    "data/netflix_clean.csv",
    index=False,
    quoting=csv.QUOTE_MINIMAL)

In [40]:
df_clean.isna().sum()

show_id           0
type              0
title             0
director          0
cast              0
country           0
date_added        0
release_year      0
rating            0
duration          0
listed_in         0
description       0
year_added        0
month_added       0
month_name        0
duration_value    0
duration_unit     0
primary_genre     0
dtype: int64

In [41]:
df_clean.duplicated().sum()

np.int64(0)

In [42]:
df_clean.dtypes

show_id                   object
type                      object
title                     object
director                  object
cast                      object
country                   object
date_added        datetime64[ns]
release_year               int64
rating                    object
duration                  object
listed_in                 object
description               object
year_added                 int32
month_added                int32
month_name                object
duration_value             int64
duration_unit             object
primary_genre             object
dtype: object

In [43]:
df_clean.describe(include="all")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,month_name,duration_value,duration_unit,primary_genre
count,8790,8790,8790,8790,8790,8790,8790,8790.000000,8790,8790,8790,8790,8790.000000,8790.000000,8790,8790.000000,8790,8790
unique,8790,2,8790,4527,7679,749,NaN,NaN,14,220,513,8758,NaN,NaN,12,NaN,3,36
top,s8807,Movie,Zubaan,Unknown,Unknown,United States,NaN,NaN,TV-MA,1 Season,"Dramas, International Movies","Paranormal activity at a lush, abandoned prope...",NaN,NaN,julio,NaN,min,Dramas
freq,1,6126,1,2621,825,2809,NaN,NaN,3205,1791,362,4,NaN,NaN,827,NaN,6126,1599
mean,NaN,NaN,NaN,NaN,NaN,NaN,2019-05-17 21:44:01.638225408,2014.183163,NaN,NaN,NaN,NaN,2018.873606,6.655859,NaN,69.934471,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,2008-01-01 00:00:00,1925.000000,NaN,NaN,NaN,NaN,2008.000000,1.000000,NaN,1.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,2018-04-06 00:00:00,2013.000000,NaN,NaN,NaN,NaN,2018.000000,4.000000,NaN,2.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-03 00:00:00,2017.000000,NaN,NaN,NaN,NaN,2019.000000,7.000000,NaN,88.500000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,2020-08-19 18:00:00,2019.000000,NaN,NaN,NaN,NaN,2020.000000,10.000000,NaN,106.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,2021-09-25 00:00:00,2021.000000,NaN,NaN,NaN,NaN,2021.000000,12.000000,NaN,312.000000,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.825466,NaN,NaN,NaN,NaN,1.573568,3.436103,NaN,50.794433,NaN,NaN

### cargar a SQL Server

In [44]:
from sqlalchemy import create_engine
import urllib

In [45]:
# Conexion a SQL Server usando SQLAlchemy y pyodbc
server   = "DESKTOP-L8IFLL2\\ALMIRCOSQL"
database = "NetflixDB"

params = urllib.parse.quote_plus(
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [46]:
# CARGAR DATAFRAME A SQL
df_clean.to_sql(name = "netflix_titles", con = engine, if_exists = "replace", index = False)

print("Tabla 'netflix_titles' cargada en NetflixDB")

Tabla 'netflix_titles' cargada en NetflixDB

In [47]:
# VERIFICAR QUE LA TABLA SE CARGÓ CORRECTAMENTE
import pandas as pd
df_check = pd.read_sql("SELECT TOP 5 * FROM netflix_titles", engine)
display(df_check)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,month_name,duration_value,duration_unit,primary_genre
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,9,septiembre,90,min,Documentaries
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,9,septiembre,2,Seasons,International TV Shows
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,9,septiembre,1,Season,Crime TV Shows
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,9,septiembre,1,Season,Docuseries
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,9,septiembre,2,Seasons,International TV Shows